### PR TITLE
Add support for laravel 8

### PR DESCRIPTION
**Pull request by lloricode**

### CODE REVIEW

**Comment by felixkiss** [comment]
thx. can you also add Laravel 8 to `.travis.yml` so it gets tested?

**Comment by lloricode** [comment]
@felixkiss done!

**Comment by matthewnessworthy** [comment]
@felixkiss Laravel 8 has been tagged and released https://github.com/laravel/framework/releases/tag/v8.0.0

**Comment by lloricode** [comment]
resolve #117

**Review by jeroenpost86 — APPROVED** [review]

**Comment by tenshiAMD** [comment]
@felixkiss A gentle followup ... hope you can merge and releases new version for the support for Laravel 8. Thanks~!

**Comment by rickgoemans** [comment]
You added Laravel 8 to PHP 7.1 and 7.2 in travis.yml while Laravel 8's composer mentions `php": "^7.3"`. So this is not a realistic test.

**Comment by matthewnessworthy** [comment]
@rickgoemans 

> You added Laravel 8 to PHP 7.1 and 7.2 in travis.yml while Laravel 8's composer mentions `php": "^7.3"`. So this is not a realistic test.

No, the code in question excludes Laravel 8 from testing with PHP 7.1 and 7.2 (since Laravel 8 is PHP ^7.3 only)

**Comment by rickgoemans** [comment]
> @rickgoemans
> 
> > You added Laravel 8 to PHP 7.1 and 7.2 in travis.yml while Laravel 8's composer mentions `php": "^7.3"`. So this is not a realistic test.
> 
> No, the code in question excludes Laravel 8 from testing with PHP 7.1 and 7.2 (since Laravel 8 is PHP ^7.3 only)

Oops my bad, I read over the exclude part. Ignore my comment(s).

**Comment by martinduefrandsen** [comment]
Any news on this?

**Comment by elijahchancey** [comment]
Please merge this!

**Comment by JieAnthony** [comment]
Please merge this!!!

**Comment by elijahchancey** [comment]
Hello?

**Comment by rickgoemans** [comment]
@felixkiss Merging or any feedback related to this PR would be great!

**Comment by elijahchancey** [comment]
@felixkiss please merge this!

**Comment by sankarsuda** [comment]
@felixkiss Please merge this. Other packages depend on this.

**Comment by djvalecillo** [comment]
please merge this! We need it.

**Comment by felixkiss** [comment]
Sorry. Didn't find the time yet to look at it. In the meantime use it like this:

```json
{
    "repositories": [
            {
                "type": "vcs",
                "url": "https://github.com/lloricode/uniquewith-validator"
            }
    ],
    "require": {
        "felixkiss/uniquewith-validator": "dev-patch-1"
    }
}
```

**Comment by elijahchancey** [comment]
@felixkiss can you merge this please? Thanks!

**Comment by rickgoemans** [comment]
I'm amazed by how bad this is managed. If a simple answer takes a month, I wonder how long a merge takes... Sorry but I hardly doubt you can't find a couple of minutes over 2 months of time for such task.

**Comment by elijahchancey** [comment]
@rickgoemans Seems a bit harsh, seeing as I'm sure Felix does this work without compensation. In any case, thanks for the hard work Felix and good luck with the merge!

**Comment by elijahchancey** [comment]
@felixkiss ping! Would love a merge whenever you can. Thanks.

**Comment by elijahchancey** [comment]
Help!? @felixkiss

**Comment by devngl** [comment]
I've been using @lloricode fork for the last month without any kind of troubles and giving it an intensive usage in production. I think it's completely safe to just merge it @felixkiss. Thanks.

**Comment by elijahchancey** [comment]
When I try to use the lloricode fork I get this error when running composer install.
```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package felixkiss/uniquewith-validator dev-patch-1 exists as felixkiss/uniquewith-validator[1.0.0, 1.0.1, 1.0.2, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0.8, 3.0.0, 3.1.0, 3.1.1, 3.1.2, 3.2.0, 3.3.0, 3.3.1, 3.4.0, dev-add-recent-laravel-versions, dev-master] but these are rejected by your constraint.
```

This is what the relevant parts of my composer.json look like:
```
"repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/lloricode/uniquewith-validator"
    }
  ],
  "require": {
    "felixkiss/uniquewith-validator": "dev-patch-1"
}
```

This is my composer install command. We're using composer 1, and haven't been able to upgrade to composer 2 yet.:
```
composer install --no-scripts --no-autoloader --no-suggest --prefer-dist
```

Anyone have any ideas on what I'm doing wrong? Thanks! @devngl @lloricode @felixkiss

**Comment by lloricode** [comment]
+

**Comment by lloricode** [comment]
up

**Comment by lloricode** [comment]
> Anyone have any ideas on what I'm doing wrong? Thanks! @devngl @lloricode @felixkiss

if any issue occur, try to fork my PR branch, then make a release then you can use your own version to your project.

note: if this merge and finally released, just run `composer clear-cache` to remove custome version in you local cache.

**Comment by felixkiss** [comment]
Sorry for the hold up. 

@lloricode What release does this require? Just a new patch version? (3.4.1)

**Comment by lloricode** [comment]
> Sorry for the hold up.
> 
> @lloricode What release does this require? Just a new patch version? (3.4.1)

yes, since no minor/major update in your library, and its just a patch to support laravel 8

**Comment by lloricode** [comment]
anyone who use my fork branch, I'm suggesting to use the original repository, I will delete my fork sooner after a couple weeks time give time adjust yours

thank you

**Pull request merged**
