### PR TITLE
Information about deleted_at in Laravel 5.

### PR DESCRIPTION
**Pull request by jakubthedeveloper**
Information about deleted_at in Laravel 5 and form request.

### CODE REVIEW

**Comment by Dreknor** [comment]
Where should your function be integrated?

**Comment by jakubkrysakowski** [comment]
@Dreknor In request class.

**Comment by anurbol** [comment]
Well instead of treating symptoms, let's solve the reason. I've made pull request for it: #92

**Comment by webenformasyon** [comment]
Maybe adding  readme some text like this can help not only for deleted_at but other fields exist in DB but not in request array.

```php
/*
if you want to check unique_with fields that does not exist in input array but exists in database you can add these values to request array and check like this
*/
        $requestData = array_merge(request()->all(), ['dbField1' => $value1, 'dbField2' => $value2]);

        //e.g for deleted ad 
       //$requestData = array_merge(request()->all(), ['dbField1' => $value1, 'deleted_at' => null]);

        $rules_create = [
            'inputField' => 'unique_with: TABLE, dbField1, dbField2',
            //'inputField' => 'unique_with: TABLE, dbField1, deleted_at', 
        ]; 
        $validator = Validator::make($requestData, $rules_create);

        if ($validator->fails()) {

        }else{

        }
```

**Comment by felixkiss** [comment]
Merged in #101  
Thanks!

**Pull request closed without merging**
