### PR TITLE
add validator instance into parameter

### LINKED ISSUE #75: Fresh installation using Laravel 5.4.* throws [trans] does not exists.
I'm using the latest laravel with the CVE patch, will report back what triggers this issue.

EDIT 2: I've tried version *.21, *.18, *.0 and they render the same error.
```
      <h1>Whoops, looks like something went wrong.</h1>\n
                                        <h2 class="block_exception clear_fix">\n
                            <span class="exception_counter">1/1</span>\n
                            <span class="exception_title"><abbr title="BadMethodCallException">BadMethodCallException</abbr> in <a title="/project/test/vendor/laravel/framework/src/Illuminate/Validation/Validator.php line 1096">Validator.php line 1096</a>:</span>\n
                            <span class="exception_message">Method [trans] does not exist.</span>\n
                        </h2>\n
                        <div class="block">\n
                            <ol class="traces list_exception">\n
       <li> in <a title="/project/test/vendor/laravel/framework/src/Illumina
```

### PR DESCRIPTION
**Pull request by rdpascua**
Closes #75 

`replaceUniqueWith` requires a sixth parameter to access to translator.

### CODE REVIEW

**Comment by felixkiss** [comment]
@rdpascua Thanks for contributing. I've pushed some changes to make this backwards compatible. If the tests pass, I will merge this tomorrow and release a new version.

**Comment by rdpascua** [comment]
Can we have this on the next release ? :smile:

**Comment by felixkiss** [comment]
@rdpascua released as v3.1.1

**Comment by Hytii** [comment]
Thanks for the quick fix guys, 3.1.1 fiex the issue for me as well

**Pull request merged**
