### PR TITLE
Implement support for Laravel 8

### PR DESCRIPTION
**Pull request by tenshiAMD**
Add support to use Laravel 8,

### CODE REVIEW

**Comment by tenshiAMD** [comment]
Related to issue https://github.com/felixkiss/uniquewith-validator/issues/117.

**Comment by tenshiAMD** [comment]
@felixkiss kindly take a look at this PR, we hope that this will be merge soon so we can use your package with Laravel 8. Thank you and more power. 🎉

**Comment by Salman98** [comment]
if everything is fine then merge this

**Comment by lloricode** [comment]
duplicate https://github.com/felixkiss/uniquewith-validator/pull/116

**Comment by tenshiAMD** [comment]
Closing this now as this already duplicate PR https://github.com/felixkiss/uniquewith-validator/pull/116 which I did not see at first.

**Pull request closed without merging**
