### PR TITLE
added Dutch language

### PR DESCRIPTION
**Pull request by tieskedh**

### CODE REVIEW

**Comment by felixkiss** [comment]
:ok_hand: 

FYI, you don't have to create a new PR to change it, you can always just push more commits to the same branch ;-)

**Comment by tieskedh** [comment]
Thx for info.
I just started with github, so I just tried something ;-)

**Comment by felixkiss** [comment]
I've been there.

Welcome! :tada:

**Comment by felixkiss** [comment]
Version `2.0.5` is out now and contains the dutch translation.

**Comment by tieskedh** [comment]
Thx

**Pull request merged**
